const PLACEHOLDERS = [
  { id: 'EXAMPLE_001', label: 'Manim', title: 'Fourier Transform Visualization' },
  { id: 'EXAMPLE_002', label: 'Remotion', title: 'Animated Data Dashboard' },
  { id: 'EXAMPLE_003', label: 'Mermaid', title: 'System Architecture Diagram' },
];

export default function Examples() {
  return (
    <section id="examples" aria-labelledby="examples-title">
      <div className="divider" />
      <div className="section">
        <p className="section-label">Examples</p>
        <h2 className="section-title" id="examples-title">See it in action.</h2>
        <p className="section-desc">
          Real renders generated by the OpenAnim engine. More coming at launch.
        </p>

        <div className="examples-grid" role="list">
          {PLACEHOLDERS.map((ex) => (
            <div className="example-card" key={ex.id} role="listitem" aria-label={`${ex.title} — coming soon`}>
              <div className="example-grid-bg" aria-hidden="true" />
              <div className="example-card-inner">
                <div className="example-placeholder">{ex.id}.mp4</div>
                <div className="example-title">{ex.title}</div>
              </div>
              <div className="example-badge">{ex.label}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
